// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE1e4nMluOFUJqc7zHsY2RmPTJdt3LjBY',
    appId: '1:110840449600:web:49aa1dd6bbfe62bd2d2da5',
    messagingSenderId: '110840449600',
    projectId: 'elibrary-1a699',
    authDomain: 'elibrary-1a699.firebaseapp.com',
    storageBucket: 'elibrary-1a699.appspot.com',
    measurementId: 'G-627S83SZTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSsx2X9feYe5_WvKheaXROmJDe2_L981M',
    appId: '1:110840449600:android:d16c603a81c1f8412d2da5',
    messagingSenderId: '110840449600',
    projectId: 'elibrary-1a699',
    storageBucket: 'elibrary-1a699.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAETVTFE6qJtP714O74NLKB2kc7DSR_xL8',
    appId: '1:110840449600:ios:592030381e5592162d2da5',
    messagingSenderId: '110840449600',
    projectId: 'elibrary-1a699',
    storageBucket: 'elibrary-1a699.appspot.com',
    iosBundleId: 'com.vscoracademy.elibrary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAETVTFE6qJtP714O74NLKB2kc7DSR_xL8',
    appId: '1:110840449600:ios:592030381e5592162d2da5',
    messagingSenderId: '110840449600',
    projectId: 'elibrary-1a699',
    storageBucket: 'elibrary-1a699.appspot.com',
    iosBundleId: 'com.vscoracademy.elibrary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCE1e4nMluOFUJqc7zHsY2RmPTJdt3LjBY',
    appId: '1:110840449600:web:ed7162e8685916642d2da5',
    messagingSenderId: '110840449600',
    projectId: 'elibrary-1a699',
    authDomain: 'elibrary-1a699.firebaseapp.com',
    storageBucket: 'elibrary-1a699.appspot.com',
    measurementId: 'G-V629FLN37S',
  );
}
